### ISSUE TITLE
Window keeps saying 'No document open'

### ISSUE THREAD

**Issue by jjyoon** [codearrows/sketch-focus#2]
I have documents open but every time I run the plug-in, doesn't seem to be working - wonder if it has to do with the update to Sketch 43?

**Comment by dakotayounger** [comment]
Same here. :(

**Comment by kamilondrej** [comment]
Heya, 

We're really sorry about that. It looks like Sketch 43 has changed some internal functionality that Sketch Focus relies on. We will release an update fixing the 'no document open' issue as soon as possible.

Regards
Kamil @ Sketch Focus

**Comment by kamilondrej** [comment]
We've just released an update which fixes the issue. Please delete the plugin and then download the latest version from sketchfocus.com.

Regards
Kamil @ Sketch Focus
